export const channelsConstants = {
    FETCH_CHANNELS_REQUEST: 'FETCH_CHANNELS_REQUEST',
    FETCH_CHANNELS_SUCCESS: 'FETCH_CHANNELS_SUCCESS',
    FETCH_CHANNELS_FAILURE: 'FETCH_CHANNELS_FAILURE',


    CREATE_CHANNEL_REQUEST: 'CREATE_CHANNEL_REQUEST',
    CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNEL_SUCCESS',
    CREATE_CHANNEL_FAILURE: 'CREATE_CHANNEL_FAILURE',

    EDIT_CHANNEL_REQUEST: 'EDIT_CHANNEL_REQUEST',
    EDIT_CHANNEL_SUCCESS: 'EDIT_CHANNEL_SUCCESS',
    EDIT_CHANNEL_FAILURE: 'EDIT_CHANNEL_FAILURE',
};