export const playitemConstants = {
    FETCH_PLAYITEMS_REQUEST: 'FETCH_PLAYITEMS_REQUEST',
    FETCH_PLAYITEMS_SUCCESS: 'FETCH_PLAYITEMS_SUCCESS',
    FETCH_PLAYITEMS_FAILURE: 'FETCH_PLAYITEMS_FAILURE',

    CREATE_PLAYITEM_REQUEST: 'CREATE_PLAYITEM_REQUEST',
    CREATE_PLAYITEM_SUCCESS: 'CREATE_PLAYITEM_SUCCESS',
    CREATE_PLAYITEM_FAILURE: 'CREATE_PLAYITEM_FAILURE',

    EDIT_PLAYITEM_REQUEST: 'EDIT_PLAYITEM_REQUEST',
    EDIT_PLAYITEM_SUCCESS: 'EDIT_PLAYITEM_SUCCESS',
    EDIT_PLAYITEM_FAILURE: 'EDIT_PLAYITEM_FAILURE',

};