export const playlistConstants = {
    FETCH_PLAYLISTS_REQUEST: 'FETCH_PLAYLISTS_REQUEST',
    FETCH_PLAYLISTS_SUCCESS: 'FETCH_PLAYLISTS_SUCCESS',
    FETCH_PLAYLISTS_FAILURE: 'FETCH_PLAYLISTS_FAILURE',

    CREATE_PLAYLIST_REQUEST: 'CREATE_PLAYLIST_REQUEST',
    CREATE_PLAYLIST_SUCCESS: 'CREATE_PLAYLIST_SUCCESS',
    CREATE_PLAYLIST_FAILURE: 'CREATE_PLAYLIST_FAILURE',

    EDIT_PLAYLIST_REQUEST: 'EDIT_PLAYLIST_REQUEST',
    EDIT_PLAYLIST_SUCCESS: 'EDIT_PLAYLIST_SUCCESS',
    EDIT_PLAYLIST_FAILURE: 'EDIT_PLAYLIST_FAILURE',

    DELETE_PLAYLIST_REQUEST: 'DELETE_PLAYLIST_REQUEST',
    DELETE_PLAYLIST_SUCCESS: 'DELETE_PLAYLIST_SUCCESS',
    DELETE_PLAYLIST_FAILURE: 'DELETE_PLAYLIST_FAILURE',

};